[[navbar]]
name = "CT Mirror"
url = "https://www.ctmirror.org/"
weight = 1

[[navbar]]
name = "Nominate An Expert"
url = "https://airtable.com/shrwKYg7fBgjHJVU3"
weight = 2
post = "_blank"

[[navbar]]
name = "Contact Us"
url = "mailto:sources@ctmirror.org"
weight = 3

[[mobile]]
name = "Home"
url = "/"
weight = 1

[[mobile]]
name = "CT Mirror"
url = "https://www.ctmirror.org/"
weight = 2

[[mobile]]
name = "Nominate An Expert"
url = "https://airtable.com/shrwKYg7fBgjHJVU3"
weight = 3
post = "_blank"

[[mobile]]
name = "Contact Us"
url = "mailto:sources@ctmirror.org"
weight = 4

[[mobile]]
name = "Donate"
url = "https://ctmirror.org/donate?campaign=7015a000000zTxmAAE"
weight = 5


[[footer]]
name = "Home"
url = "https://ctmirror.org/"
weight = 1

[[footer]]
name = "About"
url = "https://ctmirror.org/about"
weight = 2

[[footer]]
name = "FAQ"
url = "https://ctmirror.org/about/faq/"
weight = 3

[[footer]]
name = "Staff"
url = "https://ctmirror.org/about/staff/"
weight = 4

[[footer]]
name = "Newsletters"
url = "https://ctmirror.org/newsletters"
weight = 5

[[footer]]
name = "Donate"
url = "https://ctmirror.org/donate?campaign=7015a000000zTxmAAE"
weight = 6

[[footer]]
name = "Contact Us"
url = "https://ctmirror.org/contact-us/"
weight = 7


[[follow]]
name = "Facebook"
url = "https://facebook.com/CTMirror/"
weight = 1

[[follow]]
name = "Twitter"
url = "https://twitter.com/ctmirror"
weight = 2

[[follow]]
name = "Instagram"
url = "https://www.instagram.com/ctmirror/"
weight = 3

[[follow]]
name = "LinkedIn"
url = "https://www.linkedin.com/company/ctmirror/"
weight = 4

[[follow]]
name = "YouTube"
url = "https://www.youtube.com/c/theconnecticutmirror"
weight = 5

[[follow]]
name = "Google News"
url = "https://news.google.com/publications/CAAiEB2eGe8Jj40myR82AY8_MUQqFAgKIhAdnhnvCY-NJskfNgGPPzFE?hl=en-US&gl=US&ceid=US:en"
weight = 6

[[follow]]
name = "NewsBreak"
url = "https://www.newsbreak.com/channels/connecticut-mirror-512909"
weight = 7

