[[navbar]]
name = "CT Mirror"
url = "https://www.ctmirror.org/"
weight = 1

[[navbar]]
name = "Nominate An Expert"
url = "https://airtable.com/shrwKYg7fBgjHJVU3"
weight = 2

[[navbar]]
name = "Contact Us"
url = "mailto:sources@ctmirror.org"
weight = 3

[[mobile]]
name = "Home"
url = "/"
weight = 1

[[mobile]]
name = "CT Mirror"
url = "https://www.ctmirror.org/"
weight = 2

[[mobile]]
name = "Nominate An Expert"
url = "https://airtable.com/shrwKYg7fBgjHJVU3"
weight = 3

[[mobile]]
name = "Contact Us"
url = "mailto:sources@ctmirror.org"
weight = 4

[[mobile]]
name = "Support us"
url = "https://checkout.fundjournalism.org/memberform?org_id=ctmirror&campaign"
weight = 4


[[footer]]
name = "News"
link = "https://ctmirror.org/news/"
weight = 1

[[footer]]
name = "Viewpoints"
link = "https://ctmirror.org/viewpoints/"
weight = 2

[[footer]]
name = "Events"
link = "https://ctmirror.org/events"
weight = 3

[[footer]]
name = "Podcasts"
link = "https://ctmirror.org/podcasts/"
weight = 4

[[footer]]
name = "Announcements"
link = "https://ctmirror.org/announcements/"
weight = 5

[[footer]]
name = "In-Depth Series"
link = "https://ctmirror.org/series/"
weight = 6

[[footer]]
name = "Investigations"
link = "https://ctmirror.org/news/investigations/"
weight = 7

[[footer]]
name = "COVID Tracker"
link = "https://ctmirror.org/covidtracker/"
weight = 8

[[footer]]
name = "Economic Indicator Dashboard"
link = "https://ctmirror.org/economic-indicator-dashboard/"
weight = 9

[[engage]]
name = "Sign Up for Newsletters"
link = "https://ctmirror.us5.list-manage.com/subscribe?u=c546ffdc4bbb36c1f14f9c8f1&id=571d22f8e4"
weight = 10

[[engage]]
name = "Donate"
link = "https://checkout.fundjournalism.org/memberform?org_id=ctmirror&campaign=7015a000000zJPnAAM"
weight = 11

[[engage]]
name = "Submit to CT Viewpoints"
link = "https://ctmirror.org/yourviewpoint/"
weight = 12

[[engage]]
name = "Manage Your CT Mirror Membership"
link = "https://ctmirror.org/members/"
weight = 13

[[engage]]
name = "Advertise with Us"
link = "https://ctmirror.org/advertising-and-sponsorship/"
weight = 14

[[engage]]
name = "Request a Speaking Engagement"
link = "https://ctmirror.org/speaking-engagements/"
weight = 15

[[engage]]
name = "Use CT Mirror Photography"
link = "https://ctmirror.org/use-of-photography/"
weight = 16

[[learn]]
name = "About Us"
link = "https://ctmirror.org/about/"
weight = 17

[[learn]]
name = "History"
link = "https://ctmirror.org/about/history/"
weight = 18

[[learn]]
name = "Impact"
link = "https://ctmirror.org/about/impact/"
weight = 19

[[learn]]
name = "Awards"
link = "https://ctmirror.org/about/awards/"
weight = 20

[[learn]]
name = "Financial"
link = "https://ctmirror.org/about/financial/"
weight = 21

[[learn]]
name = "Strategic Plan"
link = "https://ctmirror.org/about/strategic-plan/"
weight = 22

[[learn]]
name = "Policies"
link = "https://ctmirror.org/about/policies/"
weight = 23

[[learn]]
name = "FAQ"
link = "https://ctmirror.org/about/faq/"
weight = 24

[[connect]]
name = "Board of Directors"
link = "https://ctmirror.org/about/board/"
weight = 25

[[connect]]
name = "Staff"
link = "https://ctmirror.org/about/staff/"
weight = 26

[[connect]]
name = "Community Editorial Board"
link = "https://ctmirror.org/about/community-editorial-board/"
weight = 27

[[connect]]
name = "Sponsors and Funders"
link = "https://ctmirror.org/about/sponsors/"
weight = 28

[[connect]]
name = "Donors"
link = "https://ctmirror.org/about/donors/"
weight = 29

[[connect]]
name = "Friends of The Connecticut Mirror"
link = "https://ctmirror.org/about/friends/"
weight = 30

[[connect]]
name = "Work for Us"
link = "https://ctmirror.org/work-for-us/"
weight = 31

[[connect]]
name = "Contact Us"
link = "https://ctmirror.org/contact-us/"
weight = 32
