baseURL = "https://sources.ctmirror.org/"
languageCode = "en-us"
title = "Diverse Source Database"
enableRobotsTXT = true
enableGitInfo = true
rssLimit = 50
Paginate = 25

googleAnalytics = "UA-141126362-5"
buildFuture = true

[params]
  favicon = "/img/logos/ctmirror-small.png"
  touch-icon = "/img/logos/ctmirror-logo.png"
  donate-link = "https://ctmirror.org/donate?campaign=7015a000000zTxmAAE"
  nominate-link = "https://airtable.com/shrwKYg7fBgjHJVU3"
[taxonomies]
  expertise = "expertise"
  location = "location"

[markup]
  defaultMarkdownHandler = "goldmark"

[markup.goldmark.extensions]
  definitionList = false
  footnote = false
  linkify = false
  strikethrough = false
  table = false
  taskList = false
  typographer = true

[markup.goldmark.renderer]
  unsafe = true

[outputFormats.searchindex]
  mediaType = "application/json"
  baseName = "searchindex"
  isPlainText = true

[outputs]
  home = ["html", "searchindex"]
  section = ["html"]
  taxonomy = ["html"]
  term = ["html"]

[privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = true

[build]
  writeStats = true

[minify]
  minifyOutput = true

[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "static/img/uploads"
target = "assets/img/uploads"

[[module.mounts]]
source = "static"
target = "static"

[[module.mounts]]
source = "content"
target = "content"

[[module.mounts]]
source = "pages"
target = "content"

[[module.mounts]]
source = "node_modules/@fortawesome/fontawesome-free/svgs"
target = "assets/@fontawesome"
